export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_VERIFY = "LOGIN_VERIFY";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_UNSUCCESSFUL = "LOGIN_UNSUCCESSFUL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const FETCH_SUBJECTS_SUCCESS = "FETCH_SUBJECTS_SUCCESS";
export const FETCH_SUBJECTS_FAILURE = "FETCH_SUBJECTS_FAILURE";
export const FETCH_SUBJECTS_LOADING = "FETCH_SUBJECTS_LOADING";
